apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: couchdb
stringData:
    admin-user: ENC[AES256_GCM,data:H6llUM0=,iv:hO/2pCY4ZN0QERQxb6JZz7HmsbE3vSKhtu6D5MGJP8s=,tag:KYDK7jTzwGDT53ugtOMz7Q==,type:str]
    admin-password: ENC[AES256_GCM,data:3+QkoX3ZVlvvU9OIhJBVFPiQuuqCiUmntHil+4kq+3o=,iv:4BkNn4WtjXBAF4MH/bZ9trEVR2UMqKmr/TLa3V9/mVk=,tag:v0CchbbTvrdh+UJN3l4aBA==,type:str]
    livesync-password: ENC[AES256_GCM,data:2RdlTWa8GhaeKoVQSLE/8GKo8QkVvgNxlVR1VYLo0JI=,iv:qKG6SSLfkIbI2SvYO8kZ0i28S42NkM6uFKTR18UghR0=,tag:sqhQBvcc0vmecXe2ab2qoQ==,type:str]
    livesync-server-password: ENC[AES256_GCM,data:gC9+FxtOKfwx8Qajaw5ZvaQrITWMjg1jl1PnAsd7cMw=,iv:CMDzKNw2Ao8aqb8KFlaU7qnPG/pL7HlNq6dRS79EOpE=,tag:luNssJvfMDOxCYZ9NAWfxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTEMzUEMzd3ZaRXZiMGZK
            aHlrSjZrYXI0MTBkeWliZ2QwM0Y2dTVZS2hNCnR0R3gzL1hCOEF2M2tPMFp5NmYr
            b0ZzSkpib1dMbDZDeGlrallXWitOaXcKLS0tIENHSlNNa3BjVjBFdnI5SzJQS2Fw
            RHQyV0FLeU8weFR5UHNJMXV0TmwxQVUKaULhjiMxKbDi3OknnzqNZ1YY4le+7GiO
            pTZc1u9u5Vi9fD7w5Wbg6P8jF89+DeWF+mT98XnnFQvklt4yGDLuZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fs9c9xejszarcv6c3r62efnkny06yvl6zgjlhemmyvyd2t8zq40sqtnpvg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T15:55:07Z"
    mac: ENC[AES256_GCM,data:WlM5g/gWWN1mVjWOQwuFwGW3Ugyg48WL2hq1+Enfd6Zy1RJGw1F4z+/4jlMA9odaoWQ3aWurQkjFKufXBtNhCebvcVC/DtbjNKskagzlauYw0gDjSJhaXQJSg42SqP/wyIMs2l++W60zN3lYCXpKMRFsoBHuDNlbbfTiDEadFnw=,iv:KDdgbVHmNjSHV3wPCwzWyFzyg9ocKPJTBZ39IgvlcUA=,tag:/OGEvHV+0umtuzLjMTwK9Q==,type:str]
    version: 3.13.3
