---
- name: Install librespot
  hosts: all
  become: true
  vars:
    # see https://github.com/badaix/snapcast/releases
    version: "0.31.0"
  tasks:
    - name: Install build-essential
      ansible.builtin.apt:
        name: build-essential
        state: present

    - name: Install pkg-config
      ansible.builtin.apt:
        name: pkg-config
        state: present

    - name: Install libasound2-dev
      ansible.builtin.apt:
        name: libasound2-dev
        state: present

    - name: Check if rustup is installed
      ansible.builtin.command: which rustup
      register: rustup_check
      ignore_errors: true
      changed_when: false

    - name: Download rustup installation script
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup-init.sh
        mode: "0755"
      when: rustup_check != 0

    - name: Run rustup installation script
      ansible.builtin.command: /tmp/rustup-init.sh -y
      args:
        creates: /root/.cargo/bin/rustc
      when: rustup_check != 0

    - name: Verify Rust installation
      ansible.builtin.shell: source $HOME/.cargo/env && rustc --version
      register: rustc_version
      args:
        executable: /bin/bash
      when: rustup_check != 0
      changed_when: false

    - name: Display Rust version
      ansible.builtin.debug:
        msg: "Rust version installed: {{ rustc_version.stdout }}"

    - name: Check if librespot is installed
      ansible.builtin.shell: which librespot
      register: librespot_check
      ignore_errors: true
      args:
        executable: /bin/bash
      changed_when: false

    - name: Install librespot
      ansible.builtin.shell: source $HOME/.cargo/env && cargo install librespot
      args:
        executable: /bin/bash
      when: librespot_check != 0
      changed_when: false

    - name: Copy init script
      ansible.builtin.template:
        src: ./files/librespot.service.j2
        dest: /usr/lib/systemd/system/librespot.service
        mode: "0644"
      vars:
        speaker_name: snapcast

    - name: Enable and start service
      ansible.builtin.systemd:
        name: librespot
        state: restarted
        daemon_reload: true
        enabled: true
