apiVersion: v1
kind: Secret
type: Opaque
metadata:
    annotations:
        use-subpath: "true"
    labels:
        io.kompose.service: admin
    name: admin-secret
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:Mcu8QoF74s1MUg==,iv:03yXAK8BY9f4HTNGr3oOpxUh6pB2mNB080LE9NivwkM=,tag:n8mKCsK8HbIRtS61/Gw0jQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:S+kVrVgRLPjW4JhaL8ZNSkPar0Zso4S5WZweweNghWoLxtmlNzYPDctqqWu7EYRkxlWfG8psUfoaEgU52dkqBw==,iv:HrQy9tI3m11NZduMYfCHG5wFYcZnppZ/KlyDs/yIjxg=,tag:AWDIdIy0HfwpX+59yRlc/A==,type:str]
sops:
    age:
        - recipient: age1fs9c9xejszarcv6c3r62efnkny06yvl6zgjlhemmyvyd2t8zq40sqtnpvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYXZpQXdRK250UGVacTY1
            RUtOUVR4UkU4QTNkTnhWOERicXN2T1ozcFVBCllsSU0zQStPWDAwWnc1Y2w1M3ox
            ODdGSTlrS2tUakl6V2FkRXBoNHRnREUKLS0tIEZFRDQ5QWkyeUczMEVFMk5zRXZw
            YUtEMUNwbitRdDFzdU5NczJXOGR0bGMKNKC583OIDyKWJiHhYm8Za+qhTwnW3uoq
            8jR5aLlZOru98Pc3WVVbZu+dX64ws89YoiOV9DIosKm3IPK+K9RBYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:08:59Z"
    mac: ENC[AES256_GCM,data:V3nQFhFDowMduz47CSwi0D81wCbwbvpUhvdq7qiO2FIs7UOjCddOUKYmBc+y2EctmKOBrChkAMvlnaiPUESaRGMJ6k38wRF5PoQvRZ/VviLZCckGRQM3RsfaDa0gZfUj0MYNEf1DSla5mwyDXqEnPksNBiC50s8QkKxVjUj3Pdw=,iv:g3sQlyAV8yYi0clAaE3ZT0hjKBuqqT9NtXrirVZMSDA=,tag:zS4mfFNt3MoJLsL0avb9kw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
