apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filer-data
  annotations:
    longhorn.io/recurring-job-group: s3-backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
