apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - https://raw.githubusercontent.com/senthilrch/kube-fledged/v0.10.0/deploy/kubefledged-crd.yaml
  - https://raw.githubusercontent.com/senthilrch/kube-fledged/v0.10.0/deploy/kubefledged-serviceaccount-controller.yaml
  - https://raw.githubusercontent.com/senthilrch/kube-fledged/v0.10.0/deploy/kubefledged-clusterrole-controller.yaml
  - https://raw.githubusercontent.com/senthilrch/kube-fledged/v0.10.0/deploy/kubefledged-clusterrolebinding-controller.yaml
  - https://raw.githubusercontent.com/senthilrch/kube-fledged/v0.10.0/deploy/kubefledged-deployment-controller.yaml
