---
- name: Ensure Haproxy is installed
  hosts: all
  become: true
  tasks:
    - name: Install Haproxy
      ansible.builtin.apt:
        name: haproxy
        state: present

    - name: Copy file
      ansible.builtin.copy:
        src: ./haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        mode: "0644"
      register: copy_haproxy_config

    - name: Verify config
      ansible.builtin.command: haproxy -f /etc/haproxy/haproxy.cfg -c
      when: copy_haproxy_config.changed
      changed_when: false

    - name: Install letsencrypt hook
      ansible.builtin.copy:
        src: ./letsencrypt/renewal-hooks/deploy/restart-haproxy.sh
        dest: /etc/letsencrypt/renewal-hooks/deploy/restart-haproxy.sh
        mode: "0755"

    - name: Reload haproxy
      ansible.builtin.systemd:
        name: haproxy
        state: reloaded
