apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: image-updater
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list", "get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-updater-binding
subjects:
- kind: ServiceAccount
  name: github-actions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: image-updater
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: github-actions-token
  annotations:
    kubernetes.io/service-account.name: github-actions
