apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: otel-collector
        static_configs:
          - targets: ["otel-collector:8889"]
      - job_name: homepage-rb-exporter
        static_configs:
          - targets: ["prometheus-exporter.homepage-rb.svc.cluster.local:9394"]
      - job_name: zfs_exporter
        static_configs:
          - targets: ["192.168.1.217:9134"]
      - job_name: littlebox_node_exporter
        static_configs:
          - targets: ["192.168.1.217:9100"]
      - job_name: mini_node_exporter
        static_configs:
          - targets: ["192.168.1.94:9100"]
      - job_name: ttv_node_exporter
        static_configs:
          - targets: ["192.168.1.83:9100"]
      - job_name: speaker_node_exporter
        static_configs:
          - targets: ["192.168.1.207:9100"]
