apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: otel-collector
        static_configs:
          - targets: ["otel-collector:8889"]
      - job_name: homepage-rb-exporter
        static_configs:
          - targets: ["prometheus-exporter.homepage-rb.svc.cluster.local:9394"]
