---
- name: Configure Samba
  hosts: all
  become: true
  vars:
    samba_share_name: "shared"
    samba_share_path: "/srv/samba/{{ samba_share_name }}"
    samba_share_comment: "Shared Folder"
    user_groups:
      - name: qbt_samba
        gid: 1500
      - name: qbt
        gid: 1400
      - name: sonarr
        gid: 1401
      - name: radarr
        gid: 1402
      - name: plex
        gid: 1403
      - name: bazarr
        gid: 1404
      - name: cj
        gid: 1600
      - name: carolyn
        gid: 1601
    samba_users:
      - name: qbt
        password: "{{ lookup('community.general.onepassword', 'samba qbt', field='password', vault='Infra') }}"
        uid: 1400
        groups: ["qbt", "qbt_samba"]
      - name: sonarr
        password: "{{ lookup('community.general.onepassword', 'samba sonarr', field='password', vault='Infra') }}"
        uid: 1401
        groups: ["sonarr", "qbt_samba"]
      - name: radarr
        password: "{{ lookup('community.general.onepassword', 'samba radarr', field='password', vault='Infra') }}"
        uid: 1402
        groups: ["radarr", "qbt_samba"]
      - name: plex
        password: "{{ lookup('community.general.onepassword', 'samba plex', field='password', vault='Infra') }}"
        uid: 1403
        groups: ["plex", "qbt_samba"]
      - name: bazarr
        password: "{{ lookup('community.general.onepassword', 'samba bazarr', field='password', vault='Infra') }}"
        uid: 1404
        groups: ["bazarr", "qbt_samba"]
      - name: carolyn
        password: "{{ lookup('community.general.onepassword', 'Carolyn file backup', field='password', vault='CJ Shared') }}"
        uid: 1601
        groups: ["carolyn", "cj", "qbt_samba"]
  tasks:
    - name: Install Samba packages
      ansible.builtin.package:
        name:
          - samba
          - samba-common
          - samba-client
        state: present

    - name: Create groups
      ansible.builtin.group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
        state: present
      loop: "{{ user_groups }}"

    - name: Add jutonz to groups
      ansible.builtin.user:
        name: jutonz
        groups: ["cj", "qbt_samba"]
        append: true

    - name: Create Samba users
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
        uid: "{{ item.uid }}"
        append: false
      loop: "{{ samba_users }}"

    - name: Set Samba user passwords
      ansible.builtin.shell: |
        set -o pipefail
        (echo '{{ item.password }}'; echo '{{ item.password }}') | smbpasswd -s -a {{ item.name }}
      args:
        executable: /bin/bash
      loop: "{{ samba_users }}"
      changed_when: false

    - name: Set Samba user password for jutonz
      ansible.builtin.shell: |
        set -o pipefail
        (echo '{{ password }}'; echo '{{ password }}') | smbpasswd -s -a jutonz
      args:
        executable: /bin/bash
      changed_when: false
      vars:
        password: "{{ lookup('community.general.onepassword', 'samba jutonz', field='password', vault='Infra') }}"

    # - name: Create qbt share directory
    #   ansible.builtin.file:
    #     path: "/srv/samba/qbt"
    #     state: directory
    #     mode: "0755"
    #     owner: "qbt"
    #     group: "qbt_samba"

    - name: Configure Samba
      ansible.builtin.template:
        src: files/smb.conf.j2
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart samba
      vars:
        workgroup: "WORKGROUP"

    - name: Ensure Samba service is enabled and running
      ansible.builtin.systemd:
        name: smbd
        state: started
        enabled: true

  handlers:
    - name: Restart samba
      ansible.builtin.systemd:
        name: smbd
        state: restarted
