---
all:
  hosts:
    # NOTE: Run `snapclient -l` to find correct soundcard (-s) for each host.
    ttv:
      ansible_host: ttv
      ansible_user: root
      clientOpts: --player=alsa -s6
    speaker:
      ansible_host: speaker
      ansible_user: jutonz
      clientOpts: -s3
    speaker2:
      ansible_host: speaker2
      ansible_user: jutonz
      clientOpts: -s3
