- name: Install snapclient
  hosts: all
  become: yes
  vars:
    # see https://github.com/badaix/snapcast/releases
    version: "0.31.0"
  tasks:
    - name: Install alsa-utils
      apt:
        name: alsa-utils
        state: present

    - name: Download snapclient .deb
      get_url:
        url: "https://github.com/badaix/snapcast/releases/download/v{{ version }}/snapclient_{{ version }}-1_arm64_bookworm.deb"
        dest: "/tmp/snapclient_{{ version }}.deb"

    - name: Install snapclient .deb
      apt:
        deb: "/tmp/snapclient_{{ version }}.deb"
        state: present

    - name: Copy snapclient config
      template:
        src: ./default/snapclient.j2
        dest: /etc/default/snapclient

    - name: Start snapclient
      systemd:
        name: snapclient
        state: restarted
