---
- name: Install snapclient
  hosts: all
  become: true
  vars:
    # see https://github.com/badaix/snapcast/tags
    version: "0.31.0"
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - alsa-utils
          - avahi-daemon
          - build-essential
          - cmake
          - git
          - libasound2-dev
          - libavahi-client-dev
          - libboost-all-dev
          - libexpat1-dev
          - libflac-dev
          - libopus-dev
          - libpulse-dev
          - libsoxr-dev
          - libssl-dev
          - libvorbis-dev
          - libvorbisidec-dev
        state: present
        update_cache: true

    - name: Clone snapcast repo
      ansible.builtin.git:
        repo: https://github.com/badaix/snapcast.git
        dest: /home/jutonz/code/badaix/snapcast
        version: v{{ version }}

    - name: Check if installed
      ansible.builtin.shell: command -v snapclient && snapclient --version | grep -q "v{{ version }}"
      register: installed_check
      ignore_errors: true
      changed_when: false

    - name: Create build directory
      ansible.builtin.file:
        dest: /home/jutonz/code/badaix/snapcast/build
        state: directory
        mode: "0755"
      when: installed_check.rc != 0

    - name: Configure
      ansible.builtin.command: cmake .. -DBUILD_SERVER=OFF
      args:
        chdir: /home/jutonz/code/badaix/snapcast/build
      when: installed_check.rc != 0
      changed_when: false

    - name: Compile
      ansible.builtin.command: cmake --build .
      args:
        chdir: /home/jutonz/code/badaix/snapcast/build
      when: installed_check.rc != 0
      changed_when: false

    - name: Install binary
      ansible.builtin.command: cp /home/jutonz/code/badaix/snapcast/bin/snapclient /usr/local/bin/snapclient
      when: installed_check.rc != 0
      changed_when: false

    - name: Setup service
      ansible.builtin.template:
        src: ./files/snapclient.service.j2
        dest: /usr/lib/systemd/system/snapclient.service
        mode: "0644"

    - name: Enable and start service
      ansible.builtin.systemd:
        name: snapclient
        state: restarted
        enabled: true
        daemon_reload: true
