- name: Update system packages
  hosts: all
  become: yes
  tasks:
    - name: Run apt-get upgrade
      apt:
        upgrade: yes
        update_cache: yes
      register: upgrade_output

    - name: Print upgrade output
      debug:
        var: upgrade_output.stdout_lines

    - name: Run apt-get autoremove
      command: apt-get autoremove -y
      register: autoremove_output

    - name: Print autoremove output
      debug:
        var: autoremove_output.stdout_lines
