; https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/setup_own_server.md
[couchdb]
single_node = true
uuid = 82c4888cd32cb3b75b26de815504269f
max_document_size = 50000000

[chttpd]
require_valid_user = true
max_http_request_size = 4294967296
enable_cors = true

[chttpd_auth]
require_valid_user = true

[httpd]
WWW-Authenticate = Basic realm="couchdb"
enable_cors = true

[cors]
credentials = true
origins = app://obsidian.md,capacitor://localhost,http://localhost
