# Not used, but kept around for reference. This is the original compose file
# upon which the k8s configs were built.

services:
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    ports:
      - 0.0.0.0:5232:5232
    init: true
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    deploy:
      resources:
        limits:
          memory: 256M
          pids: 50
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3
    restart: unless-stopped
    volumes:
      - /home/jutonz/radicale-test-data/data:/data
      - /home/jutonz/radicale-test-data/config:/config:ro
