apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./radicale.docker-compose.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: radicale
  name: radicale
spec:
  ports:
    - name: "5232"
      port: 5232
      targetPort: 5232
  selector:
    io.kompose.service: radicale
