---
- name: Install snapserver w/ librespot
  hosts: all
  become: true
  vars:
    # see https://github.com/badaix/snapcast/releases
    version: "0.31.0"
    arch: "amd64"
  tasks:
    - name: Install alsa-utils
      ansible.builtin.apt:
        name: alsa-utils
        state: present

    - name: Create /run/snapserver directory
      ansible.builtin.file:
        path: /run/snapserver
        state: directory
        owner: snapserver
        group: snapserver
        mode: "0755"

    - name: Download snapserver .deb
      ansible.builtin.get_url:
        url: "https://github.com/badaix/snapcast/releases/download/v{{ version }}/snapserver_{{ version }}-1_{{ arch }}_bookworm.deb"
        dest: "/tmp/snapserver_{{ version }}.deb"
        mode: "0644"

    - name: Install snapserver .deb
      ansible.builtin.apt:
        deb: "/tmp/snapserver_{{ version }}.deb"
        state: present

    - name: Copy snapserver defaults
      ansible.builtin.copy:
        src: ./files/snapserver
        dest: /etc/default/snapserver
        mode: "0644"

    - name: Copy snapserver config
      ansible.builtin.copy:
        src: ./files/snapserver.conf
        dest: /etc/snapserver.conf
        mode: "0644"

    - name: Start snapserver
      ansible.builtin.systemd:
        name: snapserver
        state: restarted
